"""
Shared ML config for router optimization.
Aligns with train_local.py and build_training_tables_local.py.
"""
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TABLES_DIR = REPO_ROOT / "training_tables"
EXPORTS_DIR = REPO_ROOT / "exports"
LOOKUPS_DIR = EXPORTS_DIR / "lookups"

# All columns that can appear in data. A column is either used for ROUTING (bucketing) or
# as a TRAINING feature (model input), never both — routing dims are excluded from model input.
FEATURE_COLS = [
    "URBANICITY", "STATE", "OCCUPATION", "OCCUPATION_GROUP", "SEGMENT_CODE",
    "AGE", "PERSON_TYPE", "EDUCATION", "ETHNICITY_GROUP_V2", "RACE_V2",
    "LANGUAGE", "MARITAL_STATUS", "RELIGION",
    "AGG_CREDIT_TIER_3RD", "AGG_CREDIT_TIER_4TH", "AGG_CREDIT_TIER_1ST", "AGG_CREDIT_TIER_2ND",
    "CARD_SPENDERS_HIGH", "CARD_SPENDERS_LOW", "EST_HH_INCOME",
    "LIFE_INS_LOYALTY_HIGH_PROPENSITY", "LIFE_INS_LOYALTY_LOW_PROPENSITY",
    "BPS", "NAV_CODE", "HOMEOWNER_RENTER",
    "LENGTH_OF_RESIDENCE", "NEW_MOVER",
    "CREDIT_BEHAVIOR_ESTABLISHED", "CREDIT_BEHAVIOR_THRIVING", "CREDIT_BEHAVIOR_UP_AND_COMING",
    "NUMBER_OF_CHILDREN_V2", "OPEN_PERSONAL_LOAN", "OPEN_STUDENT_LOAN",
    "VETERAN_IN_HOUSEHOLD", "LIKELY_TO_MOVE", "MSA",
    # Routing dimensions: now available as features so router structure can be optimized
    "GENDER", "LEAD_SOURCE_SEG", "AGE_SEG", "INCOME_BAND",
    "BPS_WEALTH", "BPS_ABILITY",
    "BPS_PRESENT", "ROKU_FLAG", "BPS_ABILITY_LETTER", "LEAD_BUCKET",
    # Engineered
    "INCOME_LOG", "HIGH_INCOME_FLAG", "AGE_70_PLUS", "AGE_LOG", "CREDIT_BEHAVIOR_SUM",
    "HAS_ANY_LOAN", "LENGTH_OF_RESIDENCE_BAND", "LIFE_INS_AFFINITY", "CARD_SPENDER_ANY",
    "CREDIT_TIER_COUNT", "NEW_MOVER_FLAG", "VETERAN_FLAG", "LIKELY_TO_MOVE_FLAG",
    "SENIOR_AFFLUENT", "LIFE_EVENT_FLAG", "BPS_PRESENT_FLAG",
    "STABILITY_BUCKET", "BPS_TIER", "CREDIT_QUALITY_BUCKET", "LIFE_READINESS_BUCKET", "FINANCIAL_ENGAGEMENT_BUCKET",
    "UNCERTAIN_LINKAGE_FLAG",
    "PRESENCE_OF_CHILDREN_V2", "CHILDREN_AGE_0_17_SCORE",
    "CHILDREN_HOUSEHOLD_0_V2", "CHILDREN_HOUSEHOLD_1_V2", "CHILDREN_HOUSEHOLD_2_V2",
    "CHILDREN_HOUSEHOLD_3_V2", "CHILDREN_HOUSEHOLD_4_PLUS_V2",
    "HH_INTEREST_CHILDREN_ITEMS_PURCHASE", "HH_INTEREST_FAMILY_ACTIVITIES", "HH_INTEREST_TOYS_PURCHASE",
    "HH_READING_CHILDRENS_BOOKS", "HH_PURCHASE_CHILDRENS_PRODUCTS", "HH_CONTRIBUTE_CHILDRENS",
    "HOME_OWNER", "OPEN_MORTGAGES_HIGH", "MORTGAGE_BALANCE_HIGHEST", "MORTGAGE_BALANCE_LOWEST",
    "EST_CUR_MORTGAGE_AMOUNT", "MORTGAGE_FREE_AND_CLEAR_HOMEOWNERS", "MORTGAGE_OPEN_LIEN",
]
# Any categorical can be used as a routing dimension; the rest are available as training features
ROUTING_CANDIDATES = [
    "URBANICITY", "STATE", "OCCUPATION", "OCCUPATION_GROUP", "SEGMENT_CODE",
    "PERSON_TYPE", "EDUCATION", "ETHNICITY_GROUP_V2", "RACE_V2", "LANGUAGE",
    "MARITAL_STATUS", "RELIGION", "BPS", "NAV_CODE", "HOMEOWNER_RENTER",
    "NUMBER_OF_CHILDREN_V2", "MSA",
    "GENDER", "LEAD_SOURCE_SEG", "AGE_SEG", "INCOME_BAND",
    "BPS_WEALTH", "BPS_ABILITY", "BPS_PRESENT", "LEAD_BUCKET",
    "LENGTH_OF_RESIDENCE_BAND", "BPS_ABILITY_LETTER",
    "STABILITY_BUCKET", "BPS_TIER", "CREDIT_QUALITY_BUCKET", "LIFE_READINESS_BUCKET", "FINANCIAL_ENGAGEMENT_BUCKET",
]
CATEGORICAL_COLS = [
    "URBANICITY", "STATE", "OCCUPATION", "OCCUPATION_GROUP", "SEGMENT_CODE",
    "PERSON_TYPE", "EDUCATION", "ETHNICITY_GROUP_V2", "RACE_V2", "LANGUAGE",
    "MARITAL_STATUS", "RELIGION", "BPS", "NAV_CODE", "HOMEOWNER_RENTER",
    "NUMBER_OF_CHILDREN_V2", "MSA",
    "GENDER", "LEAD_SOURCE_SEG", "AGE_SEG", "INCOME_BAND",
    "BPS_WEALTH", "BPS_ABILITY",     "BPS_PRESENT", "LEAD_BUCKET",
    "LENGTH_OF_RESIDENCE_BAND", "BPS_ABILITY_LETTER",
]
NUMERIC_COLS = [
    "AGE", "AGG_CREDIT_TIER_3RD", "AGG_CREDIT_TIER_4TH", "AGG_CREDIT_TIER_1ST", "AGG_CREDIT_TIER_2ND",
    "CARD_SPENDERS_HIGH", "CARD_SPENDERS_LOW", "EST_HH_INCOME",
    "LIFE_INS_LOYALTY_HIGH_PROPENSITY", "LIFE_INS_LOYALTY_LOW_PROPENSITY",
    "LENGTH_OF_RESIDENCE", "NEW_MOVER",
    "CREDIT_BEHAVIOR_ESTABLISHED", "CREDIT_BEHAVIOR_THRIVING", "CREDIT_BEHAVIOR_UP_AND_COMING",
    "OPEN_PERSONAL_LOAN", "OPEN_STUDENT_LOAN", "VETERAN_IN_HOUSEHOLD", "LIKELY_TO_MOVE",
    "INCOME_LOG", "HIGH_INCOME_FLAG", "AGE_70_PLUS", "AGE_LOG", "CREDIT_BEHAVIOR_SUM",
    "HAS_ANY_LOAN", "LIFE_INS_AFFINITY", "CARD_SPENDER_ANY",
    "CREDIT_TIER_COUNT", "NEW_MOVER_FLAG", "VETERAN_FLAG", "LIKELY_TO_MOVE_FLAG",
    "ROKU_FLAG",
    "SENIOR_AFFLUENT", "LIFE_EVENT_FLAG", "BPS_PRESENT_FLAG",
    "UNCERTAIN_LINKAGE_FLAG",
    "PRESENCE_OF_CHILDREN_V2", "CHILDREN_AGE_0_17_SCORE",
    "CHILDREN_HOUSEHOLD_0_V2", "CHILDREN_HOUSEHOLD_1_V2", "CHILDREN_HOUSEHOLD_2_V2",
    "CHILDREN_HOUSEHOLD_3_V2", "CHILDREN_HOUSEHOLD_4_PLUS_V2",
    "HH_INTEREST_CHILDREN_ITEMS_PURCHASE", "HH_INTEREST_FAMILY_ACTIVITIES", "HH_INTEREST_TOYS_PURCHASE",
    "HH_READING_CHILDRENS_BOOKS", "HH_PURCHASE_CHILDRENS_PRODUCTS", "HH_CONTRIBUTE_CHILDRENS",
    "HOME_OWNER", "OPEN_MORTGAGES_HIGH", "MORTGAGE_BALANCE_HIGHEST", "MORTGAGE_BALANCE_LOWEST",
    "EST_CUR_MORTGAGE_AMOUNT", "MORTGAGE_FREE_AND_CLEAR_HOMEOWNERS", "MORTGAGE_OPEN_LIEN",
]
TARGET_COL = "SALE_MADE_FLAG"

# Splits: train for fitting, validation for router/feature selection, test for final report only
TRAIN_FRAC = 0.6
VAL_FRAC = 0.2
TEST_FRAC = 0.2
HOLDOUT_FRAC = 0.10  # optional final holdout (from full data before train/val/test)
RANDOM_SEED = 42

# RFE: try feature counts 1 through 10 (max 10 features per model for better signal)
RFE_N_FEATURES_MIN = 1
RFE_N_FEATURES_MAX = 10
MODEL_PARAMS = {
    "n_estimators": 300,
    "max_depth": 15,
    "min_samples_split": 10,
    "min_samples_leaf": 4,
    "max_features": "sqrt",
    "random_state": 42,
    "n_jobs": -1,
    "class_weight": "balanced",
}
RFE_BASE_ESTIMATOR_PARAMS = {
    "n_estimators": 100,
    "max_depth": 10,
    "random_state": 42,
    "n_jobs": 1,
    "class_weight": "balanced",
}
RFE_STEP = 1

# Use GradientBoosting for segments with at least this many training samples (else RandomForest)
MIN_SAMPLES_FOR_GRADIENT_BOOSTING = 300

# Legacy segment key names (used in build_training_splits; also in ROUTING_CANDIDATES)
GENDER_COL = "GENDER"
LEAD_SOURCE_SEG_COL = "LEAD_SOURCE_SEG"
AGE_SEG_COL = "AGE_SEG"

# Hundreds of engineered features (log, interactions, AND/OR, counts, thresholds, crosses)
try:
    from ml.feature_engineering import get_all_engineered_names
    _ENG_NUM, _ENG_CAT = get_all_engineered_names()
    FEATURE_COLS = FEATURE_COLS + _ENG_NUM + _ENG_CAT
    NUMERIC_COLS = NUMERIC_COLS + _ENG_NUM
    CATEGORICAL_COLS = CATEGORICAL_COLS + _ENG_CAT
except Exception:
    _ENG_NUM, _ENG_CAT = [], []
